config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :boards, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :updates
  end

  resources :clients
  resources :curators do
    resource :template, controller: :templates do
      resources :elements
    end
  end

  root 'curators#index'
end

app/models/element.rb
class Element
  include Mongoid::Document

  field :name
  field :key

  validates_presence_of :name

  embedded_in :template

  before_save :set_key
  before_validation :set_key

  def key
    set_key unless self[:key]
    self[:key]
  end

  private
  def set_key
    self[:key] = name.underscore.split.join('_').gsub(/[\W]+/, '') if name
  end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_parents
  before_action :set_element, only: [:show, :edit, :update, :destroy]
  before_action :set_elements, only: [:index]

  authorize_resource :element

  def index
  end

  def show
  end

  def new
    @element = @template.elements.new
  end

  def edit
  end

  def create
    @element = @template.elements.build(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to curator_template_element_url(@curator.id, @element.id), notice: 'Element was successfully created.' }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @element.update_attributes!({name: 'Spock'})
        format.html { redirect_to curator_template_element_url(@curator.id, @element.id), notice: 'Element was successfully updated.' }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @element.destroy
    respond_to do |format|
      format.html { redirect_to curator_template_elements_url(@curator), notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def load_parents
    @curator = Curator.find(params[:curator_id])
    @template = @curator.template
  end

  def set_element
    @element  = @template.elements.find(params[:id])
  end

  def set_elements
    @elements = @template.elements
  end

  def element_params
    params.require(:element).permit(:name)
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_form.html.erb
<%#= form_for([@curator, @template, @element]) do |f| %>
<%= form_for(@element, url: @element.new_record? ? curator_template_elements_path(curator_id: @curator) : curator_template_element_path(curator_id: @curator.id, id: @element.id)) do |f| %>
  <% @element.attributes.each do |k, v| %>
    (<%= k %> <% v %>)
  <% end %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Edit Element</h1>

<%= render 'form' %>

<%= link_to 'Show', curator_template_element_path(curator_id: @curator, id: @element.id) %>
<%= link_to 'Back', curator_template_path(curator_id: @curator) %>

app/views/elements/index.html.erb
<h1>Elements</h1>
<ul id="elements">
  <% @elements.each do |element| %>
    <li><%= link_to element.name, element %></li>
  <% end %>
</ul>

app/views/elements/new.html.erb
<h1>New Element</h1>

<%= render 'form' %>

<%= link_to 'Back', curator_template_path(curator_id: @curator) %>

app/views/elements/show.html.erb
<h1><%= @element.name %></h1>
<p id="notice"><%= notice %></p>
<p><strong>Name:</strong><%= @element.name %></p>

<hr />
<%= edit_link @element %> <%= link_to 'Back', curator_template_elements_path(curator_id: @curator.id, id: @element.id) %>