config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :boards, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :updates
  end

  resources :clients
  resources :curators do
    resource :template, controller: :templates do
      resources :elements
    end
  end

  root 'curators#index'
end

app/views/templates/_form.html.erb
<%= form_for(@template, url: curator_template_path(@curator)) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% @client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', curator_template_path(@curator) %> |
<%= link_to 'Back to curator', curator_path(@curator) %>

app/views/templates/index.html.erb
<h1>Template</h1>

<%= template.name %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', curator_path(@curator) %>

app/views/templates/show.html.erb
<h1>Template: <%= @template.name %>
<p id="notice"><%= notice %></p>
<h2>Elements</h2>
<%= link_to 'show available elements for this template', curator_template_elements_path(@curator) %>

<%= edit_link @template, edit_curator_template_path(@curator) %> <%= link_to 'Back', curator_path(@curator) %>