config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :boards, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :updates
  end

  resources :clients
  resources :curators do
    resource :template, controller: :templates do
      resources :elements
    end
  end

  root 'curators#index'
end

app/models/update.rb
class Update
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  validate :has_some_data
  validate :only_has_known_fields

  field :time, type: DateTime

  embedded_in :board

  before_save :ensure_elements_are_stored
  before_save :set_time

  def elements
    valid_elements.select{ |el| attributes.key? el.key }.map { |element|
      { element => self[element.key] }
    }.inject(&:merge)
  end

  def setup_element_methods
    valid_elements.map { |el| el.key }.each { |element|
      self.class.send(:define_method, element, ->{ self[element.to_sym] })
      #self.class.send(:define_method, "#{element}=", { |value| self[element.to_sym] }
    }
  end

  private
  def has_some_data
    errors.add(
      :base, 'At least one expected element needs to be set'
    ) if valid_elements.select{ |el| !self[el.key.to_sym].nil? }.empty?
  end

  def only_has_known_fields
    attributes_without(['_id', 'elements', 'time'], self).each { |k|
      errors.add(
        :base, 
        "#{k} is not a valid element"
      ) unless valid_elements.map{ |element| element.key }.include? k.to_s
    }
  end

  def ensure_elements_are_stored
    set_elements unless self[:elements]
  end

  def set_elements
    #self[:elements] = board.elements
  end

  def set_time
    self[:time] = DateTime.now # Time.now.strftime('%Y%m%d%H%M%S%L')
  end

  def valid_elements
    (board.elements if board) or []
  end
  
  def attributes_without(keys, object)
    object.attributes.keys.select { |k, v| 
      !keys.map { |key| key.to_s }.include?(k.to_s)
    }
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_parents
  before_action :set_update, only: [:show, :edit, :update, :destroy]
  before_action :set_updates, only: [:index]

  load_and_authorize_resource :board

  def index
    @updates = @board.updates
  end

  def show
  end

  def new
    @update = @board.updates.new
    stub_update
  end

  def edit
    stub_update
  end

  def create
    @update = @board.updates.build(update_params.symbolize_keys)

    respond_to do |format|
      if @update.save
        format.html { redirect_to board_update_url(@board, @update), notice: 'Update was successfully created.' }
        format.json { render :show, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @update.update_attributes(update_params.symbolize_keys)
        format.html { redirect_to board_update_url(@board, @update), notice: 'Update was successfully updated.' }
        format.json { render :show, status: :ok, location: @update }
      else
        format.html { render :edit }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @update.destroy
    respond_to do |format|
      format.html { redirect_to board_updates_url(@board), notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def load_parents
    @board = Board.find(params[:board_id])
  end

  def set_update
    @update = @board.updates.find(params[:id])
  end

  def stub_update
    @update.setup_element_methods
  end

  def set_updates
    @updates = @board.updates
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def update_params
    params[:update]
  end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_detail.html.erb
<dl class="update">
  <dt>Time</dt>
  <dd><time datetime="<%= update.time.to_s %>"><%= update.time.to_s %></time></dd>
  <% update.elements.each do |k , v| %>
    <dt><%= k.name %></dt>
    <dd><%= v %></dd>
  <% end %>
</dl>

app/views/updates/_form.html.erb
<%= form_for([@board, @update]) do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @board.elements.each do |element| %>
    <div class="field">
      <%= f.label element.key, element.name %><br>
      <%= f.text_field element.key %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updates/_item.html.erb
<%= show_link update, board_update_path(board, update) %> <%= edit_link update, edit_board_update_path(board, update) %>
<%= render partial: 'updates/summary', locals: { update: update, board: board } %>

app/views/updates/_summary.html.erb
<dl class="update">
  <dt>Time</dt>
  <dd><time datetime="<%= update.time.to_s %>"><%= update.time.to_s %></time></dd>
  <% update.elements.select{ |k, v| !v.nil? && !v.to_s.empty? }.each do |k, v| %>
    <dt><%= k.name %></dt>
    <dd><%= v %></dd>
  <% end %>
</dl>

app/views/updates/edit.html.erb
<h1>Editing update</h1>

<%= render 'form' %>

<%= link_to 'Show', board_update_path(@board, @update) %> |
<%= link_to 'Back', board_updates_path(@board) %>

app/views/updates/index.html.erb
<h1>Listing updates</h1>

<ul id="updates">
  <% @updates.each do |update| %>
    <li><%= render partial: 'item', locals: { update: update, board: @board } %></li>
  <% end %>
</ul>

<%= new_link @board, new_board_update_path(@board) %>

app/views/updates/new.html.erb
<h1>New update</h1>

<%= render 'form' %>

<%= link_to 'Back', board_updates_path(@board) %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>Client: <%= link_to @update.board.client.name, @update.board.client %></p>
<p>Curator: <%= link_to @update.board.curator.name, @update.board.curator %></p>

<%= render partial: 'detail', locals: { update: @update } %>

<%= edit_link @update, edit_board_update_path(@board, @update) %>
<%= link_to 'Back', board_updates_path(@board) %>