config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :boards, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :updates
  end

  resources :clients
  resources :curators do
    resource :template, controller: :templates do
      resources :elements
    end
  end

  root 'curators#index'
end

app/models/board.rb
class Board
  VERSION_ID = :_timestamp

  include Mongoid::Document

  field :content

  validate :has_existing_curator
  validate :has_existing_client
  #validate :has_permitted_elements

  embeds_many :updates

  def elements
    (curator.template.elements if curator && curator.template) or []
  end

  def template
    curator.template
  end

#  def history
#    self[:content] or {}
#  end
#
#  def content
#    (self[:content][-1] if self[:content]) or {}
#  end
#
#  def content=(details)
#    return unless details
#
#    data = details.merge(VERSION_ID => get_stamp)
#
#    if self[:content] != nil
#      self[:content] << data # NOTE: could still crash if content isn't an array
#    else
#      self[:content] = [data]
#    end
#  end

  def curator
    if self[:curator] && self[:curator][:id]
      Curator.find(self[:curator][:id])
    end
  end

  def curator=(curator)
    curator = Curator.find(curator[:id]) if curator.is_a? Hash
    self[:curator] = (({ id: curator.id, name: curator.name } if curator) or {})
  end

  def client
    if self[:client] && self[:client][:id]
      Client.find(self[:client][:id])
    end
  end

  def client=(client)
    client = Client.find(client[:id]) if client.is_a? Hash
    self[:client] = (({ id: client.id, name: client.name } if client) or {})
  end

  private
  def element_names
    elements.map { |el| el.key } << VERSION_ID
  end

  alias :els :elements

  def valid_element? (field)
    !curator.template.elements.where(name: field.to_s).empty?
  end

  def has_existing_curator
    errors.add(
      :base, 'The curator does not yet exist'
    ) unless (self[:curator] && Curator.exists?(self[:curator][:id]))
  end

  def has_existing_client
    errors.add(
      :base, 'The client does not yet exist'
    ) unless (self[:client] && Client.exists?(self[:client][:id]))
  end

#  def has_permitted_elements
#    content.keys.each do |el|
#      next if el.to_sym == VERSION_ID.to_sym
#      errors.add(
#        :base, "#{el} is not a valid element"
#      ) if !element_names.include? el.to_s
#    end
#  end
#
  def get_stamp
    Time.now.strftime('%Y%m%d%H%M%S%L')
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  authorize_resource :board

  # GET /boards
  # GET /boards.json
  def index
    curator_ids = current_user.curatorships.map { |c| c.curator.id }
    client_ids = current_user.memberships.map { |c| c.client.id }
    curated_boards = Board.in('curator.id' => curator_ids)
    subscribed_boards = Board.in('client.id' => client_ids)
    @boards = Board.or(curated_boards.selector, subscribed_boards.selector)
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    respond_to do |format|
      @board = Board.new(curator: @curator, client: @client)
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(curator: @curator, client: @client)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_board
    @board = Board.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def board_params
    if params[:board] && params[:board][:curator] && params[:board][:client]
      curator_id = params[:board][:curator][:id]
      client_id = params[:board][:client][:id]
      @curator = Curator.find(curator_id) if Curator.exists?(curator_id)
      @client = Client.find(client_id) if Client.exists?(client_id)
      @template = @curator.template
    end

    params.require(:board) #.permit(:content)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Boards</h1>

<ul id="boards">
  <% @boards.each do |board| %>
    <li><%= link_to "#{board.client.name}'s #{board.curator.template.name} by #{board.curator.name}", board %> <%= edit_link board %></li>
  <% end %>
</ul>

<%#= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>Curator: <%= link_to @board.curator.name, @board.curator %></p>
<p>Client: <%= link_to @board.client.name, @board.client %></p>
<p>Template: <%= link_to @board.template.name, curator_template_path(@board.curator) %></p>

<ul id="updates">
  <% @board.updates.each do |update| %>
    <li><%= render partial: 'updates/item', locals: { update: update, board: @board } %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>